Repository marvelai-org/marvel-ai-backend, pull requests merged in 2024-12, with the labels that each got.

#132 Create ci-cd-sandbox.yml
  .github/workflows/ci-cd-sandbox.yml
Labels: type:enhancement

#110 Rubric Generator Expedition - Silicone Sages
  Dockerfile
  app/api/router.py
  app/api/tool_utilities.py
  app/api/tools_config.json
  app/features/rubric_generator/__init__.py
  app/features/rubric_generator/core.py
  app/features/rubric_generator/metadata.json
  app/features/rubric_generator/prompt/rubric-generator-prompt.txt
  app/features/rubric_generator/prompt/rubric-generator-without-context-prompt.txt
  app/features/rubric_generator/tests/__init__.py
  app/features/rubric_generator/tests/test_core.py
  app/features/rubric_generator/tools.py
  app/services/schemas.py
  requirements.txt
Labels: type:enhancement, EXPEDITION, Rubric Generator

#114 Create README.md for features
  app/features/README.md
Labels: type:documentation

#125 New Lesson Plan Generator
  app/api/tools_config.json
  app/features/lesson_plan_generator/__init__.py
  app/features/lesson_plan_generator/core.py
  app/features/lesson_plan_generator/metadata.json
  app/features/lesson_plan_generator/tests/__init__.py
  app/features/lesson_plan_generator/tests/test_core.py
  app/features/lesson_plan_generator/tools.py
  app/services/schemas.py
Labels: type:documentation, type:enhancement, EXPEDITION, type:new-feature

#126 New Writing Feedback Generator Expedition
  app/api/tools_config.json
  app/features/writing_feedback_generator/__init__.py
  app/features/writing_feedback_generator/core.py
  app/features/writing_feedback_generator/metadata.json
  app/features/writing_feedback_generator/tests/__init__.py
  app/features/writing_feedback_generator/tests/test_core.py
  app/features/writing_feedback_generator/tools.py
  app/services/schemas.py
Labels: type:documentation, type:enhancement, EXPEDITION, type:new-feature

#135 new ci-cd for main
  .github/workflows/main.yml
  .gitignore
Labels: CI/CD

#141 new readme
  README.md
  diagram.png
Labels: type:documentation

#148 New CoTeacher Agentic Workflow
  app/api/router.py
  app/assistants/classroom_support/co_teacher/assistant.py
  app/assistants/classroom_support/co_teacher/core.py
  app/assistants/classroom_support/co_teacher/metadata.json
  app/assistants/classroom_support/co_teacher/prompt/co_teacher_context.txt
  app/assistants/classroom_support/co_teacher/tools.py
  app/assistants/utils/assistants_config.json
  app/assistants/utils/assistants_utilities.py
  app/services/assistant_registry.py
  app/services/schemas.py
  app/tools/README.md
  app/tools/connect_with_them/core.py
  app/tools/connect_with_them/metadata.json
  app/tools/connect_with_them/tests/test_core.py
  app/tools/lesson_plan_generator/core.py
  app/tools/lesson_plan_generator/metadata.json
  app/tools/lesson_plan_generator/tests/test_core.py
  app/tools/presentation_generator/core.py
  app/tools/presentation_generator/metadata.json
  app/tools/presentation_generator/tests/test_core.py
  app/tools/rubric_generator/core.py
  app/tools/rubric_generator/metadata.json
  app/tools/rubric_generator/tests/test_core.py
  app/tools/rubric_generator/tools.py
  app/tools/writing_feedback_generator/core.py
  app/tools/writing_feedback_generator/metadata.json
  app/tools/writing_feedback_generator/tests/test_core.py
  app/utils/actions_for_assistants/__init__.py
  app/utils/actions_for_assistants/actions_for_assistants.py
  app/utils/actions_for_assistants/prompts/custom_prompt.txt
  app/utils/actions_for_assistants/prompts/question_generation.txt
  app/utils/actions_for_assistants/prompts/rewrite.txt
  app/utils/actions_for_assistants/prompts/summarize.txt
  app/utils/actions_for_assistants/prompts/system_prompt_question_generation_json.txt
  app/utils/actions_for_assistants/prompts/translate.txt
  app/utils/actions_for_assistants/prompts/user_prompt_question_generation_json.txt
  requirements.txt
Labels: type:enhancement, maintainers only, ASSISTANTS

#152 new README and unit tests for the Assistants
  app/assistants/README.md
  app/assistants/classroom_support/co_teacher/tests/test_core.py
Labels: type:documentation, type:enhancement, ASSISTANTS
